### ISSUE TITLE
erro ao enviar DM

### ISSUE THREAD

**Issue by tsrturbo** [pythontester192/Instagram-Bot-Scrape-DM-Users#7]
Não consegue enviar mensagem. 
abre o DM coloca o destinatario e quando click em NEXT da pagina INVALIDA..

Sorry, this page isn't available.
The link you followed may be broken, or the page may have been removed. [Go back to Instagram.](https://www.instagram.com/?hl=en)

alguém pode me ajudar?

**Comment by pythontester192** [comment]
Everything Fixed Now! Try Again.
